apiVersion: v1
kind: Secret
metadata:
  name: sample-secret2
data:
  message: SGVsbG8gV29ybGQgIQ==
  keyfile: WU9VUi1TRUNSRVQtS0VZCg==

---
apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
    - name: sample
      image: nginx:1.17.2-alpine
      env:
        - name: MESSAGE
          valueFrom:
            secretKeyRef:
              name: sample-secret2
              key: message
      volumeMounts:
        - name: secret-storage
          mountPath: /home/nginx
  volumes:
    - name: secret-storage
      secret:
        secretName: sample-secret2
        items:
          - key: keyfile
            path: keyfile
