apiVersion: v1
kind: Pod
metadata:
  name: sample
#Podの主要なSpecはcontainersとvolumes
spec:
  containers:
    - name: nginx
      image: nginx:1.17.2-alpine
      volumeMounts:
        - name: storage
          mountPath: /home/nginx
  volumes:
    - name: storage
      hostPath:
        path: /study
        type: Directory
