apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.2-alpine
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5 # 5秒後に最初のヘルスチェックを起動
            timeoutSeconds: 1  # 1秒以内に応答がなければ、コンテナを再起動する
            periodSeconds: 10 # ヘルスチェックを行う間隔（10秒）
            failureThreshold: 3 # ヘルスチェックが失敗した場合にコンテナを再起動するまでの閾値（3回）
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5 # 5秒後に最初のヘルスチェックを起動
            timeoutSeconds: 1  # 1秒以内に応答がなければ、コンテナを再起動する
            periodSeconds: 10 # ヘルスチェックを行う間隔（10秒）
            failureThreshold: 3 # ヘルスチェックが失敗した場合にコンテナを再起動するまでの閾値（3回）
          ports:
            - containerPort: 80
              protocol: TCP
          resources:  # スケールするためのリソースの閾値を設定
            requests:
              cpu: 100m # 100m = 0.1 CPU 100ミリコアと読む
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
      restartPolicy: Always
