apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    # kubectl rollout history deployment/nginxで見た際にrevisionと一緒にCHANGE CAUSEを見ることができる。それを残すためのプロパティ。
    kubernetes.io/change-cause: "Update nginx 1.17.3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      env: study
  revisionHistoryLimit: 14
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name:
        nginx
      labels:
        app: web
        env: study
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.3-alpine
