apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test # project名
  namespace: argocd
spec:
  description: test project
  sourceRepos: # 指定のRepo以外からSyncできないようにすることができる
    - "*"
  destinations: # このプロジェクトからデプロイできるclusterとnamespaceを指定。（デプロイするオブジェクトにnamespaceつけるときはここで指定する）
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
